package com.meyou.ssss.domain;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table major
 */
public class Major {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.922+08:00", comments="Source field: major.majorCode")
    private Integer majorcode;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.922+08:00", comments="Source field: major.mjr_name")
    private String mjrName;

    /**
     * Database Column Remarks:
     *   外键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.922+08:00", comments="Source field: major.collegeName_mjr")
    private String collegenameMjr;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.922+08:00", comments="Source field: major.majorCode")
    public Integer getMajorcode() {
        return majorcode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.922+08:00", comments="Source field: major.majorCode")
    public void setMajorcode(Integer majorcode) {
        this.majorcode = majorcode;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.922+08:00", comments="Source field: major.mjr_name")
    public String getMjrName() {
        return mjrName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.922+08:00", comments="Source field: major.mjr_name")
    public void setMjrName(String mjrName) {
        this.mjrName = mjrName == null ? null : mjrName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.922+08:00", comments="Source field: major.collegeName_mjr")
    public String getCollegenameMjr() {
        return collegenameMjr;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.922+08:00", comments="Source field: major.collegeName_mjr")
    public void setCollegenameMjr(String collegenameMjr) {
        this.collegenameMjr = collegenameMjr == null ? null : collegenameMjr.trim();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.922+08:00", comments="Source Table: major")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", majorcode=").append(majorcode);
        sb.append(", mjrName=").append(mjrName);
        sb.append(", collegenameMjr=").append(collegenameMjr);
        sb.append("]");
        return sb.toString();
    }
}