package com.meyou.ssss.domain;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table monitor
 */
public class Monitor {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.924+08:00", comments="Source field: monitor.mnt_id")
    private Long mntId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.925+08:00", comments="Source field: monitor.mnt_name")
    private String mntName;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.924+08:00", comments="Source field: monitor.mnt_id")
    public Long getMntId() {
        return mntId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.925+08:00", comments="Source field: monitor.mnt_id")
    public void setMntId(Long mntId) {
        this.mntId = mntId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.925+08:00", comments="Source field: monitor.mnt_name")
    public String getMntName() {
        return mntName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.925+08:00", comments="Source field: monitor.mnt_name")
    public void setMntName(String mntName) {
        this.mntName = mntName == null ? null : mntName.trim();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.925+08:00", comments="Source Table: monitor")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mntId=").append(mntId);
        sb.append(", mntName=").append(mntName);
        sb.append("]");
        return sb.toString();
    }
}