package com.meyou.ssss.domain;

import javax.annotation.Generated;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table screenshots
 */
public class Screenshots {
    //图片放大时，访问的路径
    private List<String> srcList;

    public List<String> getSrcList() {
        return srcList;
    }

    public void setSrcList(List<String> srcList) {
        this.srcList = srcList;
    }

    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    private Student student;
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.scrnsht_ID")
    private String scrnshtId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.path")
    private String path;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.submitted")
    private Boolean submitted;

    /**
     * Database Column Remarks:
     *   外键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.taskID_scrnsht")
    private Long taskidScrnsht;

    /**
     * Database Column Remarks:
     *   外键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.studentID_scrnsht")
    private Long studentidScrnsht;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.scrnsht_ID")
    public String getScrnshtId() {
        return scrnshtId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.scrnsht_ID")
    public void setScrnshtId(String scrnshtId) {
        this.scrnshtId = scrnshtId == null ? null : scrnshtId.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.path")
    public String getPath() {
        return path;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.path")
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.submitted")
    public Boolean getSubmitted() {
        return submitted;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.submitted")
    public void setSubmitted(Boolean submitted) {
        this.submitted = submitted;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.taskID_scrnsht")
    public Long getTaskidScrnsht() {
        return taskidScrnsht;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.taskID_scrnsht")
    public void setTaskidScrnsht(Long taskidScrnsht) {
        this.taskidScrnsht = taskidScrnsht;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.studentID_scrnsht")
    public Long getStudentidScrnsht() {
        return studentidScrnsht;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source field: screenshots.studentID_scrnsht")
    public void setStudentidScrnsht(Long studentidScrnsht) {
        this.studentidScrnsht = studentidScrnsht;
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.927+08:00", comments="Source Table: screenshots")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", scrnshtId=").append(scrnshtId);
        sb.append(", path=").append(path);
        sb.append(", submitted=").append(submitted);
        sb.append(", taskidScrnsht=").append(taskidScrnsht);
        sb.append(", studentidScrnsht=").append(studentidScrnsht);
        sb.append(", student=").append(student);
        sb.append("]");
        return sb.toString();
    }
}