package com.meyou.ssss.domain;

import javax.annotation.Generated;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table student
 */
public class Student {

    private College college;
    private Monitor monitor;
    private Screenshots screenshot;

    public Screenshots getScreenshot() {
        return screenshot;
    }

    public void setScreenshot(Screenshots screenshot) {
        this.screenshot = screenshot;
    }

    public College getCollege() {
        return college;
    }

    public void setCollege(College college) {
        this.college = college;
    }

    public Monitor getMonitor() {
        return monitor;
    }

    public void setMonitor(Monitor monitor) {
        this.monitor = monitor;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.934+08:00", comments="Source field: student.stu_id")
    private Long stuId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.934+08:00", comments="Source field: student.stu_name")
    private String stuName;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.934+08:00", comments="Source field: student.stu_password")
    private String stuPassword;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.grade")
    private Integer grade;

    /**
     * Database Column Remarks:
     *   外键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.monitorID_stu")
    private Long monitoridStu;

    /**
     * Database Column Remarks:
     *   外键
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.collegeName_stu")
    private String collegenameStu;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.majorName_stu")
    private String majornameStu;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.934+08:00", comments="Source field: student.stu_id")
    public Long getStuId() {
        return stuId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.934+08:00", comments="Source field: student.stu_id")
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.934+08:00", comments="Source field: student.stu_name")
    public String getStuName() {
        return stuName;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.934+08:00", comments="Source field: student.stu_name")
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.934+08:00", comments="Source field: student.stu_password")
    public String getStuPassword() {
        return stuPassword;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.stu_password")
    public void setStuPassword(String stuPassword) {
        this.stuPassword = stuPassword == null ? null : stuPassword.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.grade")
    public Integer getGrade() {
        return grade;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.grade")
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.monitorID_stu")
    public Long getMonitoridStu() {
        return monitoridStu;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.monitorID_stu")
    public void setMonitoridStu(Long monitoridStu) {
        this.monitoridStu = monitoridStu;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.collegeName_stu")
    public String getCollegenameStu() {
        return collegenameStu;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.collegeName_stu")
    public void setCollegenameStu(String collegenameStu) {
        this.collegenameStu = collegenameStu == null ? null : collegenameStu.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.majorName_stu")
    public String getMajornameStu() {
        return majornameStu;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source field: student.majorName_stu")
    public void setMajornameStu(String majornameStu) {
        this.majornameStu = majornameStu == null ? null : majornameStu.trim();
    }

    @Override
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2020-08-01T16:22:07.935+08:00", comments="Source Table: student")
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", stuId=").append(stuId);
        sb.append(", stuName=").append(stuName);
        sb.append(", stuPassword=").append(stuPassword);
        sb.append(", grade=").append(grade);
        sb.append(", monitoridStu=").append(monitoridStu);
        sb.append(", collegenameStu=").append(collegenameStu);
        sb.append(", majornameStu=").append(majornameStu);
        sb.append(", monitor=").append(monitor);
        sb.append(", college=").append(college);
        sb.append(", screenshot=").append(screenshot);
        sb.append("]");
        return sb.toString();
    }
}