spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password:
    url:
    type: com.alibaba.druid.pool.DruidDataSource
    username:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 5MB

server:
  port: 8081
  servlet:
    context-path: /ssss


mybatis:
  mapper-locations: classpath:mapper/*.xml

