spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 654321
    url: jdbc:mysql://47.93.87.136:3307/ssss?characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

server:
  port: 8081
  servlet:
    context-path: /ssss

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.meyou.ssss.domain
